import type { PortfolioData } from '../types';

export const placeholderData: PortfolioData = {
  name: "Michelle B. Rammila",
  title: "AI & Machine Learning Engineer",
  about: "Loading dynamic content... A passionate engineer specializing in machine learning and artificial intelligence, dedicated to creating innovative applications that solve real-world problems. Full profile is being generated by Gemini.",
  projects: [
    { title: 'Aura', description: 'A no-code educational chatbot that simplifies complex AI fundamentals.', tags: ['No-Code', 'Chatbot', 'AI'], githubUrl: 'https://github.com/Michellerams/Aura', liveDemoUrl: 'https://aura-flax.vercel.app/' },
    { title: 'AI Code Mentor', description: 'An AI-powered mentor for providing intelligent assistance on coding problems.', tags: ['AI', 'Python', 'Education'], githubUrl: 'https://github.com/Michellerams/AI-Code-Mentor', liveDemoUrl: 'https://ai-code-mentor-psi.vercel.app/' },
    { title: 'Creative Writer\'s Assistant', description: 'An AI writing companion for authors and marketers.', tags: ['Generative AI', 'Content'], githubUrl: 'https://github.com/Michellerams/creative-writer-s-assistant', liveDemoUrl: 'https://creative-writer-s-assistant.vercel.app/' },
    { title: 'AI ResumeBuilder', description: 'An AI-powered resume builder that creates customized, ATS-friendly resumes.', tags: ['Generative AI', 'NLP', 'React'], githubUrl: 'https://github.com/Michellerams/ResumeGenerator', liveDemoUrl: 'https://resume-generator-drab-psi.vercel.app/' },
    { title: 'SentiIQ', description: 'A sophisticated sentiment analysis tool to interpret and classify emotions in text data.', tags: ['Sentiment Analysis', 'NLP'], githubUrl: 'https://github.com/Michellerams/SentiIQ', liveDemoUrl: 'https://senti-iq.vercel.app/' },
    { title: 'SpamSentinel', description: 'An intelligent AI application designed to solve the real-world problem of spam.', tags: ['Capstone', 'Full-Stack AI'], githubUrl: 'https://github.com/Michellerams/SpamSentinel', liveDemoUrl: 'https://spam-sentinel.vercel.app/' }
  ],
  experience: [
    { company: 'Sisekelo Institute', role: 'Software Testing Learnership', duration: '2023 – 2024', description: 'Loading details...' },
    { company: 'CAPACITI', role: 'Digital Associate Intern', duration: '2023 – Present', description: 'Loading details...' }
  ],
  education: [
     { institution: 'Richfield Graduate Institute', degree: 'B.S. in Information Technology', duration: '2019 – 2021' },
     { institution: 'Thuto Pele Secondary School', degree: 'National Senior Certificate', duration: '2018' }
  ],
  certificates: Array(6).fill(0).map((_, i) => ({
    name: `Loading Certificate ${i + 1}...`,
    issuer: '...',
    date: '...',
    imageUrl: 'https://storage.googleapis.com/aistudio-hub-files/USER_CONTENT/46797a73-0b26-4277-a5ca-f3b10b00c25a.png',
    credentialUrl: '#',
  })),
  skills: [
    { name: 'Python' }, { name: 'Java' }, { name: 'JavaScript' }, { name: 'AI Prototyping' }, { name: 'SQL' }, { name: 'Generative AI' }, { name: 'Vercel' }
  ],
  competencies: [
    'Machine Learning', 'Python', 'TensorFlow', 'PyTorch', 'Data Analysis', 'Deep Learning', 'NLP', 'Computer Vision'
  ],
  contactEmail: 'bontlemichelle66@gmail.com',
  githubUrl: 'https://github.com/Michellerams',
  linkedinUrl: 'https://www.linkedin.com/in/michellebontlerammila/',
};
